## What is pandas?
Pandas is a powerful, open-source data analysis and manipulation library for Python. It's one of the most widely used tools in data science and analytics.

## Pandas Series
A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

In [59]:
## Importing pandas
import pandas as pd
import numpy as np

## Series from lists

In [60]:
# string
country = ["Bangladesh", "Pakistan", "Nepal", "Bhutan"]
pd.Series(country)

0    Bangladesh
1      Pakistan
2         Nepal
3        Bhutan
dtype: object

In [61]:
# integers
numbers = [1,3,4,6,7,8]
pd.Series(numbers)

0    1
1    3
2    4
3    6
4    7
5    8
dtype: int64

In [62]:
# custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','bangla']

pd.Series(marks,index=subjects)

maths       67
english     57
science     89
bangla     100
dtype: int64

In [63]:
# setting a name
marks = pd.Series(marks,index=subjects,name='Tanjim Marks')
marks

maths       67
english     57
science     89
bangla     100
Name: Tanjim Marks, dtype: int64

In [64]:
## series from dict
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'bangla':100
}

marks_series = pd.Series(marks,name='Tanjim Marks')
marks_series

maths       67
english     57
science     89
bangla     100
Name: Tanjim Marks, dtype: int64

## Series Attributes

In [65]:
# size
marks_series.size

4

In [66]:
# dtype
marks_series.dtype

dtype('int64')

In [67]:
# is_unique
marks_series.is_unique

pd.Series([1,1,2,3,4,5]).is_unique

False

In [68]:
# index
marks_series.index

Index(['maths', 'english', 'science', 'bangla'], dtype='object')

In [69]:
# values
marks_series.values

array([ 67,  57,  89, 100], dtype=int64)

## Series using read_csv

In [70]:
## with one column
subs = pd.read_csv('./data/subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [71]:
## with two column
vk = pd.read_csv('./data/kohli_ipl.csv',index_col='match_no')
vk

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [72]:
movies = pd.read_csv('./data/bollywood.csv',index_col='movie')
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

## Series methods

In [73]:
## head
subs.head()

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [74]:
## tail
vk.tail()

          runs
match_no
211          0
212         20
213         73
214         25
215          7

In [75]:
## sample
movies.sample(5)

                                           lead
movie
Inteqam: The Perfect Game        Manoj Bajpayee
Dil Diya Hai                      Emraan Hashmi
Saaho                      Jacqueline Fernandez
Summer 2007                         Ahraz Ahmed
Love Ke Chakkar Mein               Rishi Kapoor

In [76]:
## value_counts()
movies.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Kashmira Shah        1
Kartik Elangovan     1
Karisma Kapoor       1
Karan Sharma         1
Zulfi Sayed          1
Name: count, Length: 566, dtype: int64

In [77]:
## sort_values
vk.sort_values(by='runs', ascending=False).value_counts()

runs
0       9
1       8
12      8
9       7
35      6
       ..
64      1
44      1
45      1
29      1
113     1
Name: count, Length: 78, dtype: int64

In [78]:
# sort_index -> inplace -> movies
movies.sort_index(ascending=True)

                                        lead
movie
1920 (film)                 Rajniesh Duggall
1920: London                   Sharman Joshi
1920: The Evil Returns           Vicky Ahuja
1971 (2007 film)              Manoj Bajpayee
2 States (2014 film)            Arjun Kapoor
...                                      ...
Zindagi 50-50                    Veena Malik
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi Tere Naam         Mithun Chakraborty
Zokkomon                     Darsheel Safary
Zor Lagaa Ke...Haiya!          Meghan Jadhav

[1500 rows x 1 columns]

## Series Maths Methods

In [79]:
## count => only non-missing values total count
vk.count()

runs    215
dtype: int64

In [80]:
## sum => product 
subs.sum()

Subscribers gained    49510
dtype: int64

In [81]:
## mean

In [82]:
## median
subs.mean()

Subscribers gained    135.643836
dtype: float64

In [83]:
## mode
vk.median()

runs    24.0
dtype: float64

In [84]:
## std
movies.mode()

           lead
0  Akshay Kumar

In [85]:
## var
subs.std()

Subscribers gained    62.675023
dtype: float64

In [86]:
## min
subs.min()

Subscribers gained    33
dtype: int64

In [87]:
## max
subs.max()

Subscribers gained    396
dtype: int64

In [88]:
## describe
vk.describe()

             runs
count  215.000000
mean    30.855814
std     26.229801
min      0.000000
25%      9.000000
50%     24.000000
75%     48.000000
max    113.000000

## Indexing

In [89]:
## positive indexing
vk['runs']

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [90]:
## negative indexing => works only numerical values

## Slicing

In [91]:
vk[5:16]

          runs
match_no
6            9
7           34
8            0
9           21
10           3
11          10
12          38
13           3
14          11
15          50
16           2

In [92]:
## fancy indexing => series[[3,5,6,9]]

In [93]:
## indexing with labels => movies['Hum Tumhare Hain Sanam']